/**
 * 프롬프트 생성기
 * AI 서비스별 최적화된 프롬프트를 생성합니다.
 */

import type {
  PromptConfig,
  GeneratedPrompt,
  PromptExportBundle,
  StoryInput
} from '../types';
import {
  ALL_AI_SERVICES,
  PANEL_LABELS_KO,
  generatePromptId
} from '../types';
import { getTemplate } from '../templates';
import type { VisualDNA } from '@/types/ai';
import type { Scene } from '@/components/story/sceneConfig';

/**
 * 단일 장면에 대한 프롬프트 생성
 */
export const generatePromptForScene = (
  scene: Scene,
  visualDNA: VisualDNA,
  panelKey: 'ki' | 'seung' | 'jeon' | 'gyeol',
  sceneIndex: number,
  config: PromptConfig
): GeneratedPrompt => {
  const template = getTemplate(config.service);
  const panelLabel = PANEL_LABELS_KO[panelKey] || { label: panelKey, subtitle: '' };

  // 메인 프롬프트 생성
  const mainPrompt = template.generateMainPrompt(
    scene,
    visualDNA,
    panelKey,
    sceneIndex,
    config.language
  );

  // 네거티브 프롬프트 생성 (지원하는 서비스만)
  let negativePrompt: string | undefined;
  if (config.includeNegativePrompt && template.generateNegativePrompt) {
    negativePrompt = template.generateNegativePrompt(scene, visualDNA);
  }

  // 파라미터 생성 (Midjourney 등)
  let parameters: Record<string, string | number | boolean> | undefined;
  if (template.generateParameters) {
    parameters = template.generateParameters(config);
  }

  // 최종 포맷팅
  const finalPrompt = template.formatFinalPrompt(mainPrompt, negativePrompt, parameters);

  return {
    id: generatePromptId(config.service, panelKey, sceneIndex),
    service: config.service,
    panelKey,
    sceneIndex,
    sceneTitle: `${panelLabel.label} - 장면 ${sceneIndex}`,
    mainPrompt: finalPrompt,
    mainPromptEn: config.language === 'both' ? mainPrompt : undefined,
    negativePrompt,
    parameters: parameters as any,
    promptLength: finalPrompt.length,
    createdAt: new Date()
  };
};

/**
 * 모든 장면에 대한 프롬프트 일괄 생성
 */
export const generatePromptsForStory = (
  story: StoryInput,
  config: PromptConfig
): GeneratedPrompt[] => {
  return story.scenes.map(({ panelKey, sceneIndex, scene }) =>
    generatePromptForScene(
      scene,
      story.visualDNA,
      panelKey as 'ki' | 'seung' | 'jeon' | 'gyeol',
      sceneIndex,
      config
    )
  );
};

/**
 * 프롬프트 번들 생성 (내보내기용)
 */
export const generatePromptBundle = (
  story: StoryInput,
  config: PromptConfig
): PromptExportBundle => {
  const prompts = generatePromptsForStory(story, config);
  const serviceInfo = ALL_AI_SERVICES[config.service];

  return {
    title: story.title,
    service: config.service,
    serviceInfo,
    prompts,
    config,
    visualDNA: story.visualDNA,
    metadata: {
      totalScenes: prompts.length,
      totalCharacters: story.visualDNA.characters.filter(c => c.name).length,
      exportedAt: new Date(),
      version: '2.0'
    }
  };
};

/**
 * 프롬프트를 텍스트 파일 형식으로 변환
 */
export const promptsToText = (bundle: PromptExportBundle): string => {
  const lines: string[] = [];

  // 헤더
  lines.push(`${'='.repeat(60)}`);
  lines.push(`📝 ${bundle.title} - AI 프롬프트`);
  lines.push(`${'='.repeat(60)}`);
  lines.push('');
  lines.push(`AI 서비스: ${bundle.serviceInfo.nameKo} (${bundle.serviceInfo.name})`);
  lines.push(`총 장면 수: ${bundle.metadata.totalScenes}`);
  lines.push(`생성 시간: ${bundle.metadata.exportedAt.toLocaleString('ko-KR')}`);
  lines.push('');

  // 사용 안내
  lines.push(`${'─'.repeat(60)}`);
  lines.push('📌 사용 방법');
  lines.push(`${'─'.repeat(60)}`);
  lines.push(`1. ${bundle.serviceInfo.officialUrl} 접속`);
  lines.push('2. 아래 프롬프트를 복사하여 붙여넣기');
  lines.push('3. 이미지/영상 생성');
  lines.push('');

  if (bundle.serviceInfo.freeQuota) {
    lines.push(`💡 무료 사용량: ${bundle.serviceInfo.freeQuota}`);
    lines.push('');
  }

  // 캐릭터 정보 (있는 경우)
  const characters = bundle.visualDNA.characters.filter(c => c.name);
  if (characters.length > 0) {
    lines.push(`${'─'.repeat(60)}`);
    lines.push('👤 등장인물 설정 (일관성 유지용)');
    lines.push(`${'─'.repeat(60)}`);
    characters.forEach(char => {
      lines.push(`• ${char.name}`);
      if (char.physicalTraits) lines.push(`  외모: ${char.physicalTraits}`);
      if (char.clothing) lines.push(`  의상: ${char.clothing}`);
      if (char.distinctiveFeatures) lines.push(`  특징: ${char.distinctiveFeatures}`);
      lines.push('');
    });
  }

  // 각 장면 프롬프트
  bundle.prompts.forEach((prompt) => {
    lines.push(`${'═'.repeat(60)}`);
    lines.push(`🎬 ${prompt.sceneTitle}`);
    lines.push(`${'═'.repeat(60)}`);
    lines.push('');
    lines.push(prompt.mainPrompt);
    lines.push('');

    if (prompt.negativePrompt) {
      lines.push('【Negative Prompt】');
      lines.push(prompt.negativePrompt);
      lines.push('');
    }
  });

  // 푸터
  lines.push(`${'='.repeat(60)}`);
  lines.push('Generated by 스토리 구성 학습지');
  lines.push(`${'='.repeat(60)}`);

  return lines.join('\n');
};

/**
 * 프롬프트를 JSON 형식으로 변환
 */
export const promptsToJson = (bundle: PromptExportBundle): string => {
  const exportData = {
    title: bundle.title,
    service: {
      id: bundle.service,
      name: bundle.serviceInfo.name,
      nameKo: bundle.serviceInfo.nameKo,
      url: bundle.serviceInfo.officialUrl
    },
    visualDNA: {
      characters: bundle.visualDNA.characters,
      artStyle: bundle.visualDNA.artStyle,
      colorTone: bundle.visualDNA.colorTone,
      lighting: bundle.visualDNA.lighting,
      environment: bundle.visualDNA.environment
    },
    prompts: bundle.prompts.map(p => ({
      id: p.id,
      panelKey: p.panelKey,
      sceneIndex: p.sceneIndex,
      sceneTitle: p.sceneTitle,
      prompt: p.mainPrompt,
      negativePrompt: p.negativePrompt,
      parameters: p.parameters
    })),
    metadata: {
      totalScenes: bundle.metadata.totalScenes,
      totalCharacters: bundle.metadata.totalCharacters,
      exportedAt: bundle.metadata.exportedAt.toISOString(),
      version: bundle.metadata.version
    }
  };

  return JSON.stringify(exportData, null, 2);
};

/**
 * 클립보드에 복사할 텍스트 생성 (단일 프롬프트)
 */
export const getClipboardText = (prompt: GeneratedPrompt): string => {
  let text = prompt.mainPrompt;

  // Stable Diffusion의 경우 네거티브 프롬프트도 포함
  if (prompt.negativePrompt && prompt.service === 'stable-diffusion') {
    text = prompt.mainPrompt; // 이미 포맷팅됨
  }

  return text;
};

/**
 * 모든 프롬프트를 한 번에 복사할 텍스트 생성
 */
export const getAllPromptsClipboardText = (bundle: PromptExportBundle): string => {
  return bundle.prompts
    .map((p, i) => `[${i + 1}] ${p.sceneTitle}\n\n${p.mainPrompt}`)
    .join('\n\n' + '─'.repeat(40) + '\n\n');
};
